apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: basic-app
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters: {} # Automatically use all clusters defined within Argo CD
  template:
    metadata:
      name: '{{.name}}-ba' # 'name' field of the Secret
    spec:
      project: "default"
      source:
        repoURL: https://github.com/argo-multiverse-labs/basic-app
        targetRevision: main
        path: app-chart
      destination:
        server: '{{.server}}' # 'server' field of the secret
        namespace: apps
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
